language: go
go:
  - "1.21.x"
  - "1.16.x"

os:
  - linux
  - osx

dist: jammy
sudo: false

install: true

env:
  - GO111MODULE=on

script:
  - go get -d -v -t ./...
  - go install ./...
  - go test ./...
